spring.config.import=optional:file:.env[.properties]
spring.data.mongodb.database=${DB_NAME:}
spring.data.mongodb.uri=${MONGODB_URI:}
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration


jwt.Secret=${JWT_SECRET:}
jwt.ExpirationMs= 360000000
jwt.RefreshExpirationMs= 86400000