spring.data.mongodb.database=medico-db
spring.data.mongodb.uri=${MONGODB_URI:${MONGODB_DATABASE_URL:}}
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration


jwt.Secret=${JWT_SECRET:}
jwt.ExpirationMs= 360000000
jwt.RefreshExpirationMs= 86400000