spring.data.mongodb.database=medicines-api-db
spring.data.mongodb.uri=mongodb+srv://asadkirmani90:kruR7YP8EOQY2Kw4@cluster0.mjsrfuq.mongodb.net/?appName=Cluster0
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration


jwt.Secret=7E8B886AE01178E299B7942F50D7D032D50DF885B4E697ADF2BD950E655120AA
jwt.ExpirationMs= 360000000
jwt.RefreshExpirationMs= 86400000